
eureka:
  instance:
    hostname: eureka-server #eureka实例的主机名
  client:
    register-with-eureka: false #不把自己本身注册到eureka上
    fetch-registry: false #不从euraka上来u获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8761

